/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/_private'

// Create Virtual Routes

const PrivateIndexLazyImport = createFileRoute('/_private/')()
const PrivateTicketAbertoConsultorLazyImport = createFileRoute(
  '/_private/ticket-aberto-consultor',
)()
const PrivateTicketAbertoClienteLazyImport = createFileRoute(
  '/_private/ticket-aberto-cliente',
)()
const PrivateOpenedTicketLazyImport = createFileRoute(
  '/_private/opened-ticket',
)()
const PrivateMeusChamadosLazyImport = createFileRoute(
  '/_private/meus-chamados',
)()
const PrivateChamadoIdConsultorLazyImport = createFileRoute(
  '/_private/chamado/$id/consultor',
)()
const PrivateChamadoIdClienteLazyImport = createFileRoute(
  '/_private/chamado/$id/cliente',
)()

// Create/Update Routes

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexLazyRoute = PrivateIndexLazyImport.update({
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/index.lazy').then((d) => d.Route),
)

const PrivateTicketAbertoConsultorLazyRoute =
  PrivateTicketAbertoConsultorLazyImport.update({
    path: '/ticket-aberto-consultor',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./routes/_private/ticket-aberto-consultor.lazy').then(
      (d) => d.Route,
    ),
  )

const PrivateTicketAbertoClienteLazyRoute =
  PrivateTicketAbertoClienteLazyImport.update({
    path: '/ticket-aberto-cliente',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./routes/_private/ticket-aberto-cliente.lazy').then((d) => d.Route),
  )

const PrivateOpenedTicketLazyRoute = PrivateOpenedTicketLazyImport.update({
  path: '/opened-ticket',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/opened-ticket.lazy').then((d) => d.Route),
)

const PrivateMeusChamadosLazyRoute = PrivateMeusChamadosLazyImport.update({
  path: '/meus-chamados',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/meus-chamados.lazy').then((d) => d.Route),
)

const PrivateChamadoIdConsultorLazyRoute =
  PrivateChamadoIdConsultorLazyImport.update({
    path: '/chamado/$id/consultor',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./routes/_private/chamado/$id/consultor.lazy').then((d) => d.Route),
  )

const PrivateChamadoIdClienteLazyRoute =
  PrivateChamadoIdClienteLazyImport.update({
    path: '/chamado/$id/cliente',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./routes/_private/chamado/$id/cliente.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_private/meus-chamados': {
      id: '/_private/meus-chamados'
      path: '/meus-chamados'
      fullPath: '/meus-chamados'
      preLoaderRoute: typeof PrivateMeusChamadosLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/opened-ticket': {
      id: '/_private/opened-ticket'
      path: '/opened-ticket'
      fullPath: '/opened-ticket'
      preLoaderRoute: typeof PrivateOpenedTicketLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/ticket-aberto-cliente': {
      id: '/_private/ticket-aberto-cliente'
      path: '/ticket-aberto-cliente'
      fullPath: '/ticket-aberto-cliente'
      preLoaderRoute: typeof PrivateTicketAbertoClienteLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/ticket-aberto-consultor': {
      id: '/_private/ticket-aberto-consultor'
      path: '/ticket-aberto-consultor'
      fullPath: '/ticket-aberto-consultor'
      preLoaderRoute: typeof PrivateTicketAbertoConsultorLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/chamado/$id/cliente': {
      id: '/_private/chamado/$id/cliente'
      path: '/chamado/$id/cliente'
      fullPath: '/chamado/$id/cliente'
      preLoaderRoute: typeof PrivateChamadoIdClienteLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/chamado/$id/consultor': {
      id: '/_private/chamado/$id/consultor'
      path: '/chamado/$id/consultor'
      fullPath: '/chamado/$id/consultor'
      preLoaderRoute: typeof PrivateChamadoIdConsultorLazyImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PrivateRoute: PrivateRoute.addChildren({
    PrivateMeusChamadosLazyRoute,
    PrivateOpenedTicketLazyRoute,
    PrivateTicketAbertoClienteLazyRoute,
    PrivateTicketAbertoConsultorLazyRoute,
    PrivateIndexLazyRoute,
    PrivateChamadoIdClienteLazyRoute,
    PrivateChamadoIdConsultorLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_private"
      ]
    },
    "/_private": {
      "filePath": "_private.jsx",
      "children": [
        "/_private/meus-chamados",
        "/_private/opened-ticket",
        "/_private/ticket-aberto-cliente",
        "/_private/ticket-aberto-consultor",
        "/_private/",
        "/_private/chamado/$id/cliente",
        "/_private/chamado/$id/consultor"
      ]
    },
    "/_private/meus-chamados": {
      "filePath": "_private/meus-chamados.lazy.jsx",
      "parent": "/_private"
    },
    "/_private/opened-ticket": {
      "filePath": "_private/opened-ticket.lazy.jsx",
      "parent": "/_private"
    },
    "/_private/ticket-aberto-cliente": {
      "filePath": "_private/ticket-aberto-cliente.lazy.jsx",
      "parent": "/_private"
    },
    "/_private/ticket-aberto-consultor": {
      "filePath": "_private/ticket-aberto-consultor.lazy.jsx",
      "parent": "/_private"
    },
    "/_private/": {
      "filePath": "_private/index.lazy.jsx",
      "parent": "/_private"
    },
    "/_private/chamado/$id/cliente": {
      "filePath": "_private/chamado/$id/cliente.lazy.jsx",
      "parent": "/_private"
    },
    "/_private/chamado/$id/consultor": {
      "filePath": "_private/chamado/$id/consultor.lazy.jsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
